#ifndef __CONSTS_H__
#define __CONSTS_H__

const int BOOK_DEADLINE = 10;
const int MAGAZINE_DEADLINE = 2;
const int REFERENCE_DEADLINE = 5;
const int BOOK_FIRST_PENALTY_PERIOD = 7;
const int BOOK_SECOND_PENALTY_PERIOD = 21;
const int BOOK_FIRST_PENALTY = 2000;
const int BOOK_SECOND_PENALTY = 3000;
const int BOOK_THIRD_PENALTY = 5000;
const int MAGAZINE_FIRST_PENALTY = 2000;
const int MAGAZINE_SECOND_PENALTY = 3000;
const int REF_FIRST_PENALTY_PERIOD = 3;
const int REF_FIRST_PENALTY = 5000;
const int REF_SECOND_PENALTY = 7000;
const int MAXIMUM_NUM_OF_EXTEND = 2;
const int STUDENT_MAX_BORROWED = 2;
const int PROF_MAX_BORROWED = 5;

#endif